project/glgl/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('glgl_app.urls',namespace='glgl_app',app_name='glgl_app'))
]

project/glgl_app/urls.py
from django.conf.urls import url,include

from .import views
from .import models
from .import video
from .import search
from .import knowledge

from django.conf import settings
from django.conf.urls.static import static

from apscheduler.schedulers.background import BackgroundScheduler

def update_video_quality():
    graph = knowledge.ontology_sparql()
    videos = models.Video.objects.filter(status = 0)
    total_play = 0#用来归一化
    total_like = 0  # 用来归一化
    total_favorite = 0  # 用来归一化
    for v in videos:
        total_play += v.play
        total_like += v.like
        total_favorite += v.favorite
    for v in videos:
        try:
            play_num = float(v.play / total_play)
        except ZeroDivisionError:
            play_num = 0
        try:
            like_num = float(v.like / total_like)
        except ZeroDivisionError:
            like_num = 0
        try:
            favorite_num = float(v.like / total_favorite)
        except ZeroDivisionError:
            favorite_num = 0
        quality = float(play_num * 0.35 + like_num * 0.25 + favorite_num * 0.4)
        if quality > 0:
            #更新本体
            graph.update_video_quality("id_" + str(v.id), round(quality, 2))
            #更新关系数据库
            v.quality = round(quality, 2)
            v.save()

scheduler = BackgroundScheduler()
#This will get you a BackgroundScheduler with a MemoryJobStore named
#“default” and a ThreadPoolExecutor named “default” with a default maximum thread count of 10.
scheduler.add_job(update_video_quality, 'interval', seconds=600)
scheduler.start()

urlpatterns = [
    # ex:/
    url(r'^$', views.index, name='index'),
    #管理员首页，即今日统计
    #url(r'^adminindex/$', views.admin_index),  # add by cby 2017-04-14

    url(r'^getfeedbackdata/$', views.get_feedback_data),  # add by cby 2017-04-22

    #完整的学习方案
    url(r'^allpath/$', views.all_path),  # add by cby 2017-03-31

    url(r'^graphfeed/$', views.graph_feed),  # add by cby 2017-04-21
    # ex:/videoset/
    url(r'^videoset/$', views.video_set),
    # ex:/register/
    url(r'^register/', models.register, name='register'),
    # ex:/login/
    url(r'^login/', models.login, name='login'),
    # ex:/logout/
    url(r'^logout/', models.logout, name='logout'),
    # ex:/homepage/history
    #url(r'^homepage/(?P<user_id>[0-9]+)/', views.homepage),
    url(r'^homepage/(?P<user_id>[0-9]+)/', include([
        url(r'^$', views.homepage),
        url(r'^history/$', views.history),
    ])),# add by cby 2017-04-19

    # ex:/home/ 提供用户查看自己的信息并可以修改
    url(r'^home/', views.home, name='home'),
    # ex:/profile/
    url(r'^profile/', models.profile),

    url(r'^video/(?P<video_id>[0-9]+)/', include([
        url(r'^$', video.video_play),
        url(r'^auditpassvideo/$', models.audit_pass_video),  # add by cby 2017-04-13
        url(r'^unblockvideo/$', video.video_unblock),
        url(r'^banvideo/$', video.video_ban),
        url(r'^likethis/$', video.like),
        url(r'^favoritethis/$', video.favorite),
        # 以上三个通过js调用，当情况是：即使是使用JS，在django的MTV模式中没有模板，
        # 但是仍需要urls来指向一个后端脚本view来承担运算
        url(r'^morecomments/$', views.more_comments),
        url(r'^showpartpath/$', views.show_part_path),  # add by cby 2017-04-05
        url(r'^updateuserontology/$', models.update_user_ontology),  # add by cby 2017-04-17
        url(r'^updateuserontologysilent/$', models.update_user_ontology_silent),  # add by cby 2017-05-06
        url(r'^partfeed/$', video.part_feed),  # add by cby 2017-04-21
    ])),#上面这些放在了include里面的函数，在调用视图函数时，和继承并捕获前面路径的video_id值，一并传入视图函数中

    url(r'^send-comment/$', video.video_comment_add),#放到上面的include里面比较合理吧

    url(r'^upload/$', models.upload),
    # ex:/about/
    url(r'^about/', views.aboutus, name='about'),

    url(r'^setpassword/', models.setPassword),

    url(r'^setpassword-suc/', views.setPasswordSuc),

    #url(r'(?P<video_id>[0-9]+)/morecomments/$', views.more_comments),

    url(r'^search/', search.search),

    url(r'^check/', views.checkpage),#查看待审核视频

    url(r'^banvideo/', views.banpage),#查看已封禁的视频

#以下两个是由前端的JS请求来的
    url(r'^showtree/$', views.showtree),#add by cby 2017-03-24

    url(r'^showallpath/$', views.show_all_path),  # add by cby 2017-04-10

#知识点测试相关路径
    #注册成功之初，提供两种测试方式
    url(r'^testmode/$', views.testmode),  # add by cby 2017-04-07

    #用户非首次进行知识点测试，只能进行精确知识点测试
    url(r'^knowledge_test/$', views.knowledge_test),  # add by cby 2017-04-06

    #由前端的JS请求来的
    url(r'^getallknowledge/$', views.get_all_knowledge),  # add by cby 2017-04-06

    url(r'^getknowledgenodummy/$', views.get_knowledge_no_dummy),  # add by cby 2017-05-02
    #由前端的JS请求来的 无论是哪一种测试方式，最终都将结果提交到此处进行用户掌握程度的录入
    url(r'^submittestresults/(?P<mode>[0-9]+)/$', models.load_test_result),  # add by cby 2017-04-06

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# This helper function works only in debug mode and only if the given prefix is local
# (e.g. /media/) and not a URL (e.g. http://media.example.com/).
"""
url(r'^homepage/(?P<user_id>[0-9]+)/', include([
    url(r'^$', views.homepage)
])),  # 在这里为什么不直接调用views.homepage呢
"""

project/glgl_app/models.py
from django.contrib import auth
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.db import models
from django import forms
from django.views.decorators.http import require_http_methods
import django.utils.timezone as timezone
import os

from .knowledge import *


# 用户额外信息——对系统自带的User类进行扩展：采用新建一个profile model，并与User建立一对一关系
class UserExtraProfile(models.Model):
    user = models.OneToOneField(User)  # User是系统自带的类/model
    headimage = models.ImageField(upload_to='headimages',
                                  default='default/default_headimage.jpg')  # 头像
    description = models.CharField(max_length=50, default='')  # 个人描述
    testornot = models.BooleanField(default=False)  # add by cby 2017-04-07 识别用户是否进行过测试，当创建了知识体系时，将其置为True

    def __str__(self):
        return self.user.username  # access user model 里面的只需通过User model即可


# 视频
class Video(models.Model):
    title = models.CharField(max_length=100, default='title')  # 标题
    video = models.FileField(upload_to='videos')  # 视频文件
    cover = models.ImageField(upload_to='covers',
                              default='default/default_headimage.jpg')  # 封面
    description = models.CharField(max_length=200, default='空')  # 描述
    uploader = models.ForeignKey(User, related_name='uploader')  # UP主

    teacher = models.CharField(max_length=5, default='空')  # 讲师 add by cby 2017-04-20
    tag = models.CharField(max_length=30, default='')  # 知识点 add by cby 2017-04-11
    difficulty = models.FloatField(default=0) #视频相对大纲难度 add by cby 2017-04-11
    quality = models.FloatField(default=0)  # 视频难度 add by cby 2017-04-28

    play = models.IntegerField(default=0)  # 播放数

    like = models.IntegerField(default=0)  # 点赞数
    like_list = models.ManyToManyField(UserExtraProfile)  # 点赞列表

    time = models.DateTimeField(auto_now=False, auto_now_add=True)  # 上传时间
    status = models.IntegerField(default=0)  # 状态——用来标记视频是否被管理员禁封

    # add by 2017-04-04
    favorite = models.IntegerField(default=0)  # 收藏数
    favorite_list = models.ManyToManyField(UserExtraProfile, related_name="favorite_list")  # 收藏列表
    # end add by cby

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # ——相当于在这里给视频创建了url
        return '/video/%u' % self.pk  # pk是主码，并未在上面定义
        # 另外 video前有‘/’说明不继承之前的，没了就要继承之前的
        # 需要经视频的主码self.pk存入视频本体中，视频质量信息则从本体中取出来


# 评论
class Comment(models.Model):
    user = models.ForeignKey(User)  # 评论者
    video = models.ForeignKey(Video)  # 评论视频
    # 因为设置了多对一的关系，使得在浏览器请求视频时，
    # video会自动反向查询并将结果形成comment_set放在video中
    content = models.CharField(max_length=400)  # 内容
    cdate = models.DateTimeField(default=timezone.now)  # 评论时间，

    # 一旦创建该类的实例，cdate就保存一个当前时间，所以在创建实例时只需要将前三项赋值即可

    # ForeignKey意味着多对一
    # Comment VS User：Many To One ：一个用户可以对应多条评论，但一条评论只能对应一个用户
    # Comment VS Video：Many To One ：一个视频可以有多条评论，但一条评论只能对应一个视频
    # 感觉数据库设计很重要，尤其是梳理表与表之间的关系

    def __str__(self):
        return self.user.username


# 消息提醒 目前还没有用到，以后会用
class Notification(models.Model):
    NContent = models.CharField(max_length=50)
    NUser = models.ForeignKey(UserExtraProfile)#b不要只和UserExtraProfile关联


# 历史记录 用来记录用户的学习进度和情况add by cby 2017-04-19
class History(models.Model):
    HUser = models.ForeignKey(User)  # 该条历史执行者
    HVideo = models.ForeignKey(Video)  # 视频
    hscore = models.FloatField(default=0)  # 当时执行者打分score
    hchange = models.FloatField(default=0)  # 当时该视频对应的知识点的achieve改变量change

    hdate = models.DateTimeField(default=timezone.now)  # 历史创建的时间

    dummy = models.BooleanField(default=False)  # add by cby 2017-05-06 用来区分呢是否是拟打分

    def __str__(self):
        return self.HUser.username


# 部分学习方案的反馈 add by cby 2017-04-21
class PartFeedback(models.Model):
    PVideo = models.ForeignKey(Video)  #反馈对象视频
    PUser = models.ForeignKey(User) #该条反馈执行者
    pfeed = models.BooleanField(default=False)
    pdate = models.DateTimeField(default=timezone.now)  # 反馈时间

    def __str__(self):
        return self.PVideo.title

# 知识图谱的反馈 add by cby 2017-04-21
class GraphFeedback(models.Model):
    GUser = models.ForeignKey(User)  # 该条反馈执行者
    gfeed = models.BooleanField(default=False)
    gdate = models.DateTimeField(default=timezone.now)  # 反馈时间

    def __str__(self):
        return self.GUser.username


# 上传视频表单——这是一个表单模型，为什么要用表单呢，因为表单多了一些系统自带的验证
class VideoUploadForm(forms.ModelForm):  # 继承自forms.ModelForm 上传过来的数据先存到这个数据表中，再在视图函数中
    class Meta:
        model = Video  # 复用
        fields = ['title', 'description', 'cover', 'video', 'tag', 'difficulty', 'teacher']
        # 将Video类中的部分filed放出来让他们成为接口——当前表单的字段，限定属性


# 关于表单模型与普通模型的区别 参看http://www.cnblogs.com/hhh5460/p/4526613.html
# 当前这个模型是复用在models里已经设计好了的类Video(就是数据库的表)，利用这个类的（部分）信息
# （此例中使用了'title', 'description', 'cover', 'video', 'tag', 'category'）
# 来作为该表单的模型。复用方法就是在子类Meta中 进行model和fields的赋值

# 注册
def register(request, error_msg=""):  # 给变量先赋值个空字符串，这样就不需要外来一定要传进来参数
    if request.user.is_authenticated():  # 先验证访问者的当前状态，若已登陆 就跳回个人信息
        # 只有再逻辑出现错误时才会发生这种情况，我觉得这部分写的有点浪费，后期试试tests文件
        return HttpResponseRedirect("/homepage/")
    if request.method == 'POST':
        input_is_valid = False
        # 收集信息，未填则为空
        username = request.POST['username'] if request.POST['username'] else ""
        password1 = request.POST['password1'] if request.POST['password1'] else ""
        password2 = request.POST['password2'] if request.POST['password2'] else ""
        email = request.POST['email'] if request.POST['email'] else ""
        description = request.POST['description'] if request.POST['description'] else ""
        # 判断是否达成注册条件
        error_msg = "错误"  # 和input_is_valid一样先提前写着
        if not username:
            error_msg = "请输入用户名"
        elif not (password1 and password2):
            error_msg = "请输入密码"
        elif not email:
            error_msg = "请输入邮箱"
        elif not description:
            error_msg = "请输入个人描述"
        elif password1 != password2:
            error_msg = "两次密码不一致"
        elif len(password1) < 6:
            error_msg = "密码长度小于6位"
        elif User.objects.filter(username=username):
            error_msg = "用户名已经存在"
            username = ""  # 擦去
        elif User.objects.filter(email=email):
            error_msg = "邮箱已经注册"
            email = ""  # 擦去
        else:
            # 可注册
            input_is_valid = True
            user = User.objects.create_user(username=username,
                                            password=password1,
                                            email=email)  # 这三项是User类必需的
            user.save()
            thisProfile = UserExtraProfile(user=user,
                                           description=description)  # 怎么搞的这三项成立必填项呢？默认设置？
            thisProfile.save()
            return HttpResponseRedirect("/login/")#注册成功跳到登陆界面 以新身份登陆
            #return render(request, "glgl_app/login.html", context={"username": username})
        if not input_is_valid:
            # 注册信息有误
            return render(request, "glgl_app/register.html", {'error': error_msg,
                                                              'username': username,
                                                              'email': email})
    else:
        return render(request, "glgl_app/register.html")


# 知识点测试结果写入用户本体中
def load_test_result(request, mode, error_msg=""):
    if request.user.is_authenticated():
        if request.method == 'POST':
            user_id = "id" + str(request.user.id)# 用用户id创建实例
            graph = ontology_sparql(dataset="user", userid=user_id)
            u_profile = User.objects.get(username=request.user.username).userextraprofile#不是'UserExtraProfile' 而是userextraprofile
            #mode1、2和3都是用户本体未建立的情况才出现的,所以用户add不用update，此时用update会where查询不到任何东西
            if mode == "1":  # 快速模式 零基础
                if graph.create_user_instance():
                    if graph.add_same_achieve(0.0):
                        u_profile.testornot = True
                        u_profile.save(update_fields=['testornot'])
                        return HttpResponseRedirect("/homepage/%s/" % str(request.user.id))
                    else:
                        return render(request, "glgl_app/knowledge_test.html",
                                      context={"error_msg": "用户知识体系创建失败，请重新进行测试"})
                else:
                    return render(request, "glgl_app/knowledge_test.html",
                                  context={"error_msg": "用户知识体系创建失败，请重新进行测试"})
            elif mode == "2":
                if graph.create_user_instance():
                    if graph.add_same_achieve(0.2):
                        u_profile.testornot = True
                        u_profile.save(update_fields=['testornot'])
                        return HttpResponseRedirect("/homepage/%s/" % str(request.user.id))
                    else:
                        return render(request, "glgl_app/knowledge_test.html",
                                      context={"error_msg": "用户知识体系创建失败，请重新进行测试"})
                else:
                    return render(request, "glgl_app/knowledge_test.html",
                                  context={"error_msg": "用户知识体系创建失败，请重新进行测试"})
            elif mode == "3":
                if graph.create_user_instance():
                    if graph.add_same_achieve(1.0):
                        u_profile.testornot = True
                        u_profile.save(update_fields=['testornot'])
                        return HttpResponseRedirect("/homepage/%s/" % str(request.user.id))
                    else:
                        return render(request, "glgl_app/knowledge_test.html",
                                      context={"error_msg": "用户知识体系创建失败，请重新进行测试"})
                else:
                    return render(request, "glgl_app/knowledge_test.html",
                                  context={"error_msg": "用户知识体系创建失败，请重新进行测试"})
            elif mode == "4": #进入该模式必须是用户本体achieve属性值全为0

project/glgl_app/templates/glgl_app/banvideo.html
{% extends "glgl_app/base.html" %}

{% block title %}封禁视频列表{% endblock %}

{% block extracss %}
	<link href="/static/css/index.css" rel="stylesheet">
{% endblock %}

{% block content %}
	<div>
		<h2>已封禁视频</h2>
	</div>
	{% for video in checking_videos %}
	<div class="col-md-3 col-sm-6 col-xs-12 dd-grid">
		<figure class="effect-sadie">
			<img src="/media/{{video.cover}}" alt="img02" class="img-responsive center-block"/>
			<figcaption>
			<h2>{{ video.title }}</h2>
			<p>up主: {{ video.uploader.username }} <br>播放量: {{ video.play }}</p>
			<a href="{{ video.get_absolute_url }}">View more</a>
			</figcaption>
		</figure>
	</div>
	{% endfor %}
{% endblock %}
<!--这个模板和check模板只差了两个标题，可以少一个的，后期再说-->

project/glgl_app/templates/glgl_app/loadallPath.html
{% extends "glgl_app/base.html" %}

{% block title %}学习方案{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="/static/css/kn_other_map.min.css">
<style>
.vz-weighted_tree-viz {
    overflow:scroll;
}
</style><!--这个是设置滚动条元素-->
{% endblock %}

{% block content %}
<div class="mainCol padding15px addcolor">
    <div class="setborder"><!--是setborder让它有了阴影-->
        <div id="mapRow" class="kl_str"></div><!--在loadmap函数里面选定了id为mapRow的gaidiv进行扩展的-->
    </div>
</div>
{% endblock %}

{% block extrascripts %}
<script type="text/javascript" src="/static/js/load_force.js"></script>
<script type="text/javascript" src="/static/weight/lib/d3.min.js" charset="utf-8"></script>
<script>
    $(function () {
        var dw=1140,dh=940,options;
        options = {
            width: dw,
            height: dh
        };
        $.get('/showpath/',
            function(data){
            var nodes = data.nodes,lines = data.lines
            loadMap(options, nodes, lines);
        })
    });
</script>
{% endblock %}

project/glgl_app/templates/glgl_app/notadmin.html
{% extends "glgl_app/base.html" %}

{% block title %}你不是管理员{% endblock %}

{% block content %}
<div class="m-row" style="text-align: center">
	<div>你不是管理员！</div>
	<a href = "/" class = "btn btn-default btn-lg" style="margin-top: 10px">返回主页</a>
</div>
{% endblock %}

project/glgl_app/templates/glgl_app/setpassword-suc.html
{% extends "glgl_app/base.html" %}

{% block title %}密码修改成功{% endblock %}

{% block content %}
	<div class="m-row" style="text-align: center">
		<div>密码修改成功，请重新登录</div>
		<div class="m-row" style="text-align: center">
			<a href = "/" class = "btn btn-default btn-lg" style="margin-top: 10px">返回主页</a>
		</div></div>
{% endblock %}

project/glgl_app/templates/glgl_app/setpassword.html
{% extends "glgl_app/base.html" %}

{% block title %}修改密码{% endblock %}

{% block content %}
<div class="panel panel-default panel-body">
	<form class="form-base" onsubmit="return check(this)" action="/setpassword/" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="m-row">
			<label for="id_password">原密码:</label>
			<input type="password" placeholder="输入您的原密码" class="form-control" name="password" maxlength="128"> 
		</div>

		<div class="m-row">
			<label for="id_newpassword1">新密码:</label>
			<input type="password" class="form-control" placeholder="不少于6个字符" id="id_newpassword1" name="newpassword1" maxlength="128">
		</div>
		
		<div class="m-row">
			<label for="id_newpassword2">再次输入新密码:</label>
			<input type="password" class="form-control" placeholder="" id="id_newpassword2" name="newpassword2" maxlength="128">
		</div>
		
		<div class="m-row">
			{{ error }}
		</div>
		<div class="m-row" style="text-align: center">
			<input type="submit" class="btn btn-success btn-lg" style="margin-top: 10px" value="重置密码">
		</div>
		<div class="m-row" style="text-align: center">
			<a href = "/" class = "btn btn-default btn-lg" style="margin-top: 10px">返回主页</a>
		</div>
	</form>
</div>
{% endblock %}

project/glgl_app/templates/glgl_app/upload.html
{% extends "glgl_app/base.html" %}

{% block title %}上传视频{% endblock %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="http://cdn.gbtags.com/ztree/3.5/zTreeStyle.css">
{% endblock %}

{% block content %}
    <div class="center">
        <div class="col-sm-12 col-md-6 box-left">
            <div class="panel panel-success">
                <div class="panel-heading">请点击下方的知识树为上传的视频添加知识标签</div>
                <div class="panel-body">

                    <ul class="ztree" id="ztree2"></ul>
                </div>
            </div>
        </div><!--知识标签选择区域-->
        <div class="col-sm-12 col-md-6 box-left">
            <div class="panel panel-success">
                <div class="panel-heading">上传</div>
                <div class="panel-body">
                {% if error %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <!--data-dismiss?aria-label?-->
                            <span aria-hidden="true">
                                &times;<!--显示结果是× 乘号-->
                            </span>
                        </button>
                        <strong>Error!</strong> {{ error }}<!--strong是加粗-->
                    </div>
                {% endif %}
                <div id="show-error"></div>
                <form class="form-base" onsubmit="return check(this)" action="/upload/" method="post" enctype="multipart/form-data"> <!--action为空，即仍请求当前url-->
                    {% csrf_token %}
                    <div class="m-row">
                        <label for="id_video">文件*</label>
                        <input type="file" accept="video/*" class="form-control" id="id_video" name="video">
                        <!--accept="video/*"规定了会接受的文件类型-->

                        <label for="id_cover">封面</label>
                        <input type="file" accept="image/*" class="form-control" id="id_cover" name="cover">

                        <label for="id_title">标题*</label>
                        <input type="text" class="form-control" placeholder="请输入标题" id="id_title" maxlength="100" name="title"
                               value="{{ form.title.value }}">
                        <!--name的用处显现出来了：form.title.value中的title就是该元素实例的name——错！2017.02.28
                        form.title.value中的title是传进来的表单form中的属性，这个表单是复用video模型，所以更进一步说这个title是video模型的title属性
                        .value就是取该属性的值，若不是表单，比如是video实例，那些直接video.title-->

                        <label for="id_description">描述</label>
                        <input type="text" class="form-control" placeholder="请输入视频描述" id="id_description" name="description"
                               value="{{ form.description.value }}">

                        <label for="id_description">视频讲师</label>
                        <input type="text" class="form-control" placeholder="请输入视频描述" id="id_teacher" name="teacher"
                               value="{{ form.description.teacher }}">

                        <label for="id_tag">知识标签*</label>
                        <input type="text" class="form-control" placeholder="" id="id_tag" name="tag"
                               value="{{ form.tag.value }}">

                        <label for="id_demand">该知识的大纲要求为</label>
                        <input id="id_demand" class ="form-control" name = "demand">
                        <!--需要写点啥-->
                        </input>

                        <label for="id_difficulty">视频难度*</label>
                        <select id="id_difficulty" class ="form-control" name = "difficulty">
                        <option value="0.2">相对大纲要求是基础</option>
                        <option value="0.6">基本符合大纲要求</option>
                        <option value="1.0">完全符合大纲要求</option>
                        </select>
                    </div>

                    <div class="m-row" style="text-align: center">
                        <input type="submit" class="btn btn-success btn-lg" style="margin-top: 10px" value="上传视频">
                    </div>

                    <div class="m-row" style="text-align: center">
                        <a href = "/" class = "btn btn-default btn-lg" style="margin-top: 10px">返回主页</a>
                    </div>
                </form>
                </div>
            </div>
        </div><!--上传区域-->
    </div>
{% endblock %}

{% block extrascripts %}
<script type="text/javascript" src="/static/js/form-check.js"></script>
<script type="text/javascript" src="/static/js/check_video-upload-form.js"></script>
<!--里面有个check函数，而且这里面用了这一个Script中的函数。也就是说这两个Scripts组成了check函数-->
<script type="text/javascript" src="http://cdn.gbtags.com/ztree/3.5/jquery.ztree.all-3.5.min.js"></script>

<script>

  var setting =
   {
      check: {
        enable: false,
        chkboxType: { "Y": "ps", "N": "ps" }
      },
      data: {
        simpleData: {
          enable: false
        }
      },
      view:{
        showIcon:false,
        nameIsHTML: true
      },
      callback : { //回调函数
            onClick : onClick   //右键事件
        },
    };

    var zTree;
    var treeNodes;

    $(function(){
        $.ajax({
            async : false,
            cache:false,
            type: 'GET',
            dataType : "json",
            url: "/getknowledgenodummy/",//请求的action路径
            error: function () {//请求失败处理函数
                alert('请求失败');
            },
            success:function(data){ //请求成功后处理函数。
                //alert(data);
                treeNodes = data.children;   //把后台封装好的简单Json格式赋给treeNodes
            }
        });
        $.fn.zTree.init($("#ztree2"), setting, treeNodes);
        //zTree = $("#tree").zTree(setting, treeNodes);
    });

    function onClick(event, treeId, treeNode, clickFlag){
        document.getElementById('id_tag').value = treeNode.name;
        document.getElementById('id_demand').value = treeNode.demand;
        //alert(name+"zzz");
    }
</script>
{% endblock %}

project/glgl_app/templates/glgl_app/upload_success.html
{% extends "glgl_app/base.html" %}

{% block title %}上传成功{% endblock %}

{% block content %}
<h3>上传成功，请等待管理员审核</h3>
{% endblock %}

project/glgl_app/templates/glgl_app/user_score.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>请为自己的学习效果打分</title>
</head>

<body>
    <div>
        <div id="video-id" style="display: none;">{{ user_id }}</div>
        <label>该视频对应的知识点是：{{ knowledge }}</label>
        <label>教学大纲对该知识点的要求是：{{ demand }}</label>
        <form action="spreadingactivate/" method="POST">
            {% csrf_token %}
            <input type="radio" name="score" checked="checked" value="{{ user_id }}:0.0" />完全没学懂<br />
            <input type="radio" name="score" value="{{ user_id }}:0.2" />学会了一点<br />
            <input type="radio" name="score" value="{{ user_id }}:0.6"/>基本学会了<br />
            <input type="radio" name="score" value="{{ user_id }}:1.0" />完全学会了
            <button id="finish">提交</button>
        </form>
	</div>
</body>
</html>

project/glgl_app/templates/glgl_app/video-notfound.html
{% extends "glgl_app/base.html" %}

{% block title %}视频无法播放{% endblock %}

{% block content %}
<h3>对不起，该视频无法播放。</h3>
<h3>可能的原因：</h3>
<h3>视频链接不存在</h3>
<h3>视频未通过审核</h3>
<h3>up主自行删除</h3>
<h3>您不是管理员</h3>
<h3>您尚未登录，无法验证您的权限</h3>
{% endblock %}